name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]
        django-version: [3.0, 3.1]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tooling
        run: |
          python -mpip install poetry codecov
      - name: Install dependencies
        run: |
          poetry install
      - name: Setup Django ${{ matrix.django-version }}
        run: |
          poetry run pip install django==${{ matrix.django-version }}
      - name: Lint with flake
        run: |
          poetry run flake8 django_simple_task
      - name: Test with pytest
        run: |
          poetry run py.test --cov=./django_simple_task/
      - name: Upload coverage to codecov
        run: |
          codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
